apiVersion: v1
kind: Resource
metadata:
  name: cassandra-a
spec:
  template:
    - name: test1
      user_keyspace: tst_user
      account_keyspace: tst_account
      infrastructure:
        - cassandra-a/test

    - name: sit
      user_keyspace: sit_user
      account_keyspace: sit_account
      infrastructure:
        - cassandra-a/test

    - name: alpha
      user_keyspace: user
      account_keyspace: account
      infrastructure:
        - cassandra-a/alpha

    - name: prod
      user_keyspace: user
      account_keyspace: account
      infrastructure:
        - cassandra-a/prod